### ISSUE TITLE
Add a '--quiet' or '--verbose' to [not] output the generated json in the console

### ISSUE THREAD

**Issue by le-yams** [Ozee-io/fga-transformer-cli#1]
Hello,

I would like to use this cli in a CI job but the fact that it outputs the generated json add a lot of noise in the job logs.
It would be nice to be able to deactivate that output (with a `--quiet` option for example).

I'd even go further and suggest that, as the main objective is to generated a file, the default behavior would be to not output the json in the console. The output could be enabled with a dedicated option (the classic `--verbose` for example).

I could initiate a PR if that is something you would be ok with.

**Comment by le-yams** [comment]
I initiated a PR #2

**Comment by rorychatterton** [comment]
Merged. Thanks!
